apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zv2ln1aig-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zv2ln1aig-dotnet-basic-gitops